name: Unity Package

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Unity Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo "Assets/ModelInstanceCollection.meta" > metaList
          find Assets/ModelInstanceCollection/ -name \*.meta >> metaList

      - name: Building Unity Package
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "ModelInstanceCollection.unitypackage"
          include-files: metaList

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ModelInstanceCollection
          path: ModelInstanceCollection.unitypackage
      - name: Publish artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ModelInstanceCollection.unitypackage"
          name: "ModelInstanceCollection"
          commit: "master"
          tag: "${{github.ref}}"
